INSERT INTO settings (setting_key, setting_value, setting_group) VALUES
('site_name', '{SITE_NAME}', 'general'),
('site_url', '{SITE_URL}', 'general'),
('site_phone', '{SITE_PHONE}', 'general'),
('site_email', '{ADMIN_EMAIL}', 'general'),
('site_color', '#2563eb', 'appearance'),
('site_logo_url', '', 'appearance'),
('city_name', '{CITY_NAME}', 'location'),
('city_lat', '{CITY_LAT}', 'location'),
('city_lng', '{CITY_LNG}', 'location'),
('city_radius', '{CITY_RADIUS}', 'location'),
('company_name', '', 'company'),
('company_address', '', 'company'),
('company_siret', '', 'company'),
('estimation_coef_neuf', '1.15', 'estimation'),
('estimation_coef_renove', '1.05', 'estimation'),
('estimation_coef_bon', '1.00', 'estimation'),
('estimation_coef_travaux', '0.85', 'estimation'),
('estimation_coef_refaire', '0.70', 'estimation'),
('estimation_coef_terrasse', '1.05', 'estimation'),
('estimation_coef_parking', '1.03', 'estimation'),
('estimation_coef_piscine', '1.07', 'estimation'),
('estimation_coef_vue', '1.04', 'estimation'),
('relance_j3_active', '1', 'emails'),
('relance_j7_active', '1', 'emails'),
('relance_j14_active', '0', 'emails'),
('notification_new_lead', '1', 'notifications'),
('notification_rdv', '1', 'notifications'),
('webhook_url', '', 'integrations'),
('calendly_url', '', 'integrations'),
('whatsapp_number', '', 'integrations'),
('google_analytics_id', '', 'integrations'),
('google_ads_id', '', 'integrations'),
('maintenance_mode', '0', 'system'),
('debug_mode', '0', 'system');

INSERT INTO modules (name, slug, icon, is_active) VALUES
('Dashboard', 'dashboard', 'fas fa-home', 1),
('Leads', 'leads', 'fas fa-users', 1),
('Google Ads', 'google-ads', 'fas fa-ad', 1),
('Utilisateurs', 'users', 'fas fa-user-shield', 1),
('Paramètres', 'settings', 'fas fa-cog', 1)
ON DUPLICATE KEY UPDATE
name = VALUES(name),
icon = VALUES(icon),
is_active = VALUES(is_active);
